spring:
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://${DBHOST:localhost}:${DBPORT:3306}/${DBNAME:tcs}?useUnicode=true&characterEncoding=utf8&useSSL=${USE_SSL:false}&serverTimezone=UTC
    username: ${DBUSER:root}
    password: ${DBPASSWORD:}
  flyway:
    password: ${DBPASSWORD:}
    schemas: ${DBNAME:tcs}
  elasticsearch:
    rest:
      uris: http://localhost:9200
  jpa:
    show_sql: false

tcs.server:
  name: ${TCS_HOST:localhost}
  port: ${TCS_PORT:80}

tcs.service:
  url: ${TCS_SERVER_URL:http://${tcs.server.name}:${tcs.server.port}/tcs}

tcs.client:
  rate.limit: ${TCS_CLIENT_RATE_LIMIT:100}
  bulk.rate.limit: ${TCS_CLIENT_BULK_RATE_LIMIT:10}

app:
  aws:
    access:
      key:
        id: ${AWS_ACCESS_KEY_ID}
    secret:
      access:
        key: ${AWS_SECRET_ACCESS_KEY}

logging:
  file: ${LOG_DIR:${HOME}}/sync.log

kc:
  realm: ${KC_REALM:lin}
  client:
    id: ${KC_CLIENT_ID:api-tokens}
  server:
    url: ${KC_SERVER_URL}
  username: ${KC_USERNAME}
  password: ${KC_PASSWORD}
  timeout: ${KC_TIMEOUT:10000}

slack:
  api:
    token: ${SLACK_API_TOKEN:}
  job:
    notification-channel: spaml

# enable.es.search: true
enable.es.search: false
