spring:
  devtools:
    restart:
      enabled: false
  datasource:
    url: jdbc:mysql://${DBHOST}:${DBPORT}/${DBNAME}?useUnicode=true&characterEncoding=utf8&useSSL=${USE_SSL}
    username: ${DBUSER}
    password: ${DBPASSWORD}
  flyway:
    password: ${DBPASSWORD}
    schemas: ${DBNAME}
  elasticsearch:
    rest:
      uris: ${ES_URLS}

logging:
  file: ${LOG_DIR:${HOME}}/sync.log
  level:
    uk.nhs: debug

slack:
  api:
    token: ${SLACK_API_TOKEN}
  job:
    notification-channel: dev-monitoring

enable.es.search: ${ENABLE_ES_SEARCH}

application:
  aws:
    access:
      key:
        id: ${AWS_ACCESS_KEY_ID}
    secret:
      access:
        key: ${AWS_SECRET_ACCESS_KEY}
    region: ${AWS_REGION:eu-west-2}
