spring:
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://${DBHOST:localhost}:${DBPORT:3306}/${DBNAME:tcs}?useUnicode=true&characterEncoding=utf8&useSSL=${USE_SSL:false}&serverTimezone=UTC
    username: ${DBUSER:root}
    password: ${DBPASSWORD:}
  flyway:
    password: ${DBPASSWORD:}
    schemas: ${DBNAME:tcs}
  elasticsearch:
    rest:
      uris: ${ES_URLS:http://localhost:9200}
  jpa:
    show_sql: false

logging:
  file: ${LOG_DIR:${HOME}}/sync.log

kc:
  realm: ${KC_REALM:lin}
  client:
    id: ${KC_CLIENT_ID:api-tokens}
  server:
    url: ${KC_SERVER_URL}
  username: ${KC_USERNAME}
  password: ${KC_PASSWORD}
  timeout: ${KC_TIMEOUT:10000}

slack:
  api:
    token: ${SLACK_API_TOKEN:}
  job:
    notification-channel: spaml

# enable.es.search: true
enable.es.search: false

application:
  cron:
    recordResendingJob: ${APPLICATION_CRON_RECORDRESENDINGJOB:-}
  aws:
    kinesis:
      streamName: ${AWS_KINESIS_STREAM_NAME:}
    sqs:
      queueUrl: ${AWS_SQS_QUEUE_URL:}
